name: Build and Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build-only-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # 사용하고자 하는 .NET 버전

      - name: Build
        run: dotnet build --configuration Release "./Test GithubActions/Test GithubActions.csproj"

      - name: Test
        run: dotnet test --configuration Release "./TestProject/TestProject.csproj"

      - name: Check Build and Test Status
        if: ${{ failure() }}
        run: echo "Build or test failed! All checks have failed."
