name: Build and Test PR

on:
  pull_request:
    branches:
      - working

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # 사용하고자 하는 .NET 버전

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal

      - name: Merge PR if tests pass
        if: ${{ success() }}
        uses: repo-sync/github-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
          branch: ${{ github.head_ref }}
