name: Build Only PR

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  build-only-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # 사용하고자 하는 .NET 버전

      - name: Build
        run: dotnet build --configuration Release ./Test GithubActions/Test GithubActions


      - name: Check Build Status
        if: ${{ failure() }}
        run: echo "Build failed! All checks have failed."

      # 추가적인 단계들
